snowdrop/spring-boot-bom

README.md
pom.xml

Add OpenTracing support.

---

.circleci/config.yml
.circleci/delete_gh_release.sh
.circleci/settings.xml

Attempt to enable releasing the BOM by creating a dummy github tag

---

pom.xml

ActiveMQ is not a supported component so no need to have it in the BOM

Remove activemq

---

pom.xml

https://issues.jboss.org/browse/SB-1073
For now I'm just aligning them with Spring Boot 2.1.1. Once we get to the final release we should review this and if needed align with prod versions.

Upgrade tomcat and undertow

---

pom.xml

https://issues.jboss.org/browse/SB-856

Upgrade CXF to 3.2.7

---

pom.xml

update versions for dekorate

---

pom.xml

Could you guys, please, take a look? Thx!

chorus : bump versions for 2.1.13 release

---

pom.xml

Hi, 
Could you please review this changes and let me know if you agree or not? 
Spring Boot 2.2.6 is expected for tomorrow so I did already the change!
thank you!!

chore: update dependencies versions

---

pom.xml

Changes for release 2.2.6.RELEASE

Changes for release 2.2.6.RELEASE

---

pom.xml

update to the dekorate version that support the  manifest generation

---

pom.xml

To version `3.9.0.Final` and the booster to `3.2.1.Final`.

Updated resteasy version

---

pom.xml

update the dekorate version to 0.11.8

update the dekorate version to 0.11.8

---

.circleci/config.yml
README.adoc
pom.xml

Updated the `pom.xml` file as well as the README references for testing purposes, to see if our productization process works with the new spring-boot structure generated by Gradle.

feat: release beta1 for version 2.3.2

---

pom.xml

fixed the spring-boot version that was missing and updated the overridden section with the correct version numbers

fix: updated versions from the parent project

---

pom.xml

See https://issues.redhat.com/browse/RESTEASY-2672

chore: bump resteasy sb starter version

---

pom.xml

Need to wait for the newly released artifact to get synced with Maven Central.

Upgrade Narayana Spring Boot to 2.4.1

---

pom.xml

This is the `pom.xml` cooked for 2.3.4.

fixes for release 2.3.4

---

pom.xml

...for the actual released version

chore: update opentracing-spring-jaeger-web-starter version

---

pom.xml

chore: test ENTSBT-316

---

pom.xml

pom update for release 2.2.11

---

release.yml

Updated `release.yml` file for release 2.3.6. It's still missing the release and eol dates.

updated properties for release 2.3.6

---

pom.xml

Adapt the GPG plugin configuration so the release process, and gpg sign, can be called from a batch process

feat: adapt gpg configuration to batch execution

---

release.yml
release_template.yml

* updated the assignee for the tracing JIRA as requested in TRACING-1703

chore: updated the assignee for the tracing JIRA

---

release-2.3.10.yml
release_template.yml

chore: release file for 2.3.10
